model_name: bert-base-uncased
max_length: 100
epochs: 60
batch_size: 45
repetitions: 3
data_path: dbpedia
lvl: 3
test_model_lvl1: 'saved_models/bert-base-uncased/dbpedia/lvl1/trained_flatt__/100T_20e_40b/Run2/model'
test_model_lvl2: 'saved_models/bert-base-uncased/dbpedia/lvl2/trained_hierarchical_per_label/100T_60e_45b'
hierar: hierarchical
lable_type: per_label
test_labels_type: _