model_name: bert-base-uncased
max_length: 100
epochs: 60
batch_size: 45
repetitions: 1
data_path: dbpedia
lvl: 3
test_model: 'saved_models/bert-base-uncased/dbpedia/lvl1/trained_flatt__/100T_20e_40b/Run2/model'
second_test_model: 'saved_models/bert-base-uncased/dbpedia/lvl1/trained_flatt__/100T_20e_40b/Run2/model'
hierar: hierarchical
lable_type: per_label
test_labels_type: _